# @package network
defaults:
  - _base
  - _self_

network_type: "sudeepdit_repa"
emb_dim: 1024  # Used as d_model
num_layers: 8  # Used as depth
dropout: 0.0
timestep_emb_dim: 512
align_depth: 2
projector_dim: 2048
z_dims: [1024]

# SudeepDiT specific configs
n_heads: 4  # Number of attention heads
timestep_emb_type: "positional"  # Options: positional, sinusoidal, fourier
