# @package task
defaults:
  - can_ph_state
  - _self_

# Override for mh variant
env_type: "mh"
# dataset_filename: "robomimic/can/mh/low_dim.hdf5"
dataset_path: "data/robomimic/can/mh/low_dim_v15.hdf5"
