# @package task
defaults:
  - square_ph_image
  - _self_

# Override for mh variant
env_type: "mh"
# dataset_filename: "robomimic/square/mh/image.hdf5"
dataset_path: "data/robomimic/square/mh/image_v15.hdf5"
