# @package task
defaults:
  - robomimic_base
  - _self_

env_name: "transport"
obs_type: "image"
env_type: "ph"

dataset_paths:
  - data/robomimic/transport/ph/image_v15.hdf5
  - data/robomimic/transport/image_rollouts_clipped_truncate.hdf5
abs_action: false
action_type: "delta"
filter_success: true

max_episode_steps: 700
render_obs_key: "shouldercamera0_image"

# Required keys
horizon: 10
act_dim: 14  # Dual-arm delta uses raw 7D per arm (2 * (3 pos + 3 rot + 1 grip))

shape_meta:
  action:
    shape:
      - 14
  obs:
    shouldercamera0_image:
      shape:
        - 3
        - 84
        - 84
      type: rgb
    shouldercamera1_image:
      shape:
        - 3
        - 84
        - 84
      type: rgb
    robot0_eye_in_hand_image:
      shape:
        - 3
        - 84
        - 84
      type: rgb
    robot1_eye_in_hand_image:
      shape:
        - 3
        - 84
        - 84
      type: rgb
    robot0_eef_pos:
      shape:
        - 3
      type: low_dim
    robot0_eef_quat:
      shape:
        - 4
      type: low_dim
    robot0_gripper_qpos:
      shape:
        - 2
      type: low_dim
    robot1_eef_pos:
      shape:
        - 3
      type: low_dim
    robot1_eef_quat:
      shape:
        - 4
      type: low_dim
    robot1_gripper_qpos:
      shape:
        - 2
      type: low_dim

num_envs: 4
