# @package task
defaults:
  - transport_ph_state
  - _self_

# Override for mh variant
env_type: "mh"
# dataset_filename: "robomimic/transport/mh/low_dim.hdf5"
dataset_filename: "data/robomimic/transport/mh/low_dim_v15.hdf5"
